# Generated by Django 5.1.4 on 2025-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=20)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar'), ('GBP', 'British Pound')], default='EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('pc', 'PC'), ('component', 'Component')], max_length=9)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
